// `<Html>`'s cascade answers most rules without matching them: a rule that
// is the class or the id it is filed under matches every element its bucket
// is asked for (`keyOnly`), and one that names an ancestor no ancestor of an
// element is matches none of them (`Cascade._hasAncestors`). What those two
// promise is checked against the matcher asked of every rule and every
// element: documents and selectors are generated by seed, with descendants,
// children, siblings, `:not()`, `:is()`, attributes and positions — what
// the fast paths have to stay out of the way of — and each element's rules
// have to be the ones css-select matches.
import { test } from 'node:test';
import assert from 'node:assert';
import type { Element } from 'domhandler';
import { is } from 'css-select';

import { Cascade } from '../src/html/css/cascade.js';
import { parseStylesheet } from '../src/html/css/parse.js';
import type { RootLook } from '../src/html/css/style.js';
import { HtmlSource } from '../src/html/dom.js';

const LOOK: RootLook = {
  color: '#000000',
  fontFamily: 'sans-serif',
  fontSize: 16,
  monoFamily: 'monospace',
  linkColor: '#0000ee',
  borderColor: '#808080',
  mutedColor: '#666666',
  background: '#ffffff',
  colorScheme: 'light',
  surface: '#ffffff',
  controlPadY: 4,
  controlBorder: 1,
  controlRadius: 4,
};

function rng(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const TAGS = ['div', 'p', 'span', 'section', 'ul', 'li', 'em', 'a'];
const CLASSES = ['a', 'b', 'c', 'd', 'e', 'md:x'];
const IDS = ['x', 'y', 'z'];

/** A document of nested elements with classes, ids and an attribute. */
function documentOf(next: () => number): string {
  let n = 0;
  const element = (depth: number): string => {
    n += 1;
    const tag = TAGS[Math.floor(next() * TAGS.length)];
    const classes = CLASSES.filter(() => next() < 0.3);
    const attrs =
      (classes.length ? ` class="${classes.join(' ')}"` : '') +
      (next() < 0.15 ? ` id="${IDS[Math.floor(next() * IDS.length)]}"` : '') +
      (next() < 0.2 ? ` data-k="${Math.floor(next() * 3)}"` : '');
    let inside = '';
    if (depth < 6 && n < 400) {
      const kids = Math.floor(next() * 4);
      for (let i = 0; i < kids; i += 1) inside += element(depth + 1);
    }
    return `<${tag}${attrs}>${inside || 'x'}</${tag}>`;
  };
  let body = '';
  for (let i = 0; i < 6; i += 1) body += element(0);
  return `<html><head></head><body>${body}</body></html>`;
}

/** A selector of one to three compounds. */
function selectorOf(next: () => number): string {
  const escape = (name: string) => name.replace(':', '\\:');
  const compound = (): string => {
    let text = '';
    if (next() < 0.4) text += TAGS[Math.floor(next() * TAGS.length)];
    const extras = 1 + Math.floor(next() * 2);
    for (let i = 0; i < extras; i += 1) {
      const r = next();
      if (r < 0.5)
        text += `.${escape(CLASSES[Math.floor(next() * CLASSES.length)])}`;
      else if (r < 0.62) text += `#${IDS[Math.floor(next() * IDS.length)]}`;
      else if (r < 0.72) text += `[data-k="${Math.floor(next() * 3)}"]`;
      else if (r < 0.8)
        text += `:not(.${escape(CLASSES[Math.floor(next() * CLASSES.length)])})`;
      else if (r < 0.88)
        text += `:is(.a, #${IDS[Math.floor(next() * IDS.length)]})`;
      else if (r < 0.94) text += ':first-child';
      else text += `:nth-child(${1 + Math.floor(next() * 3)})`;
    }
    return text || '*';
  };
  const combinators = [' ', ' > ', ' + ', ' ~ '];
  let selector = compound();
  const more = Math.floor(next() * 3);
  for (let i = 0; i < more; i += 1) {
    selector = `${compound()}${combinators[Math.floor(next() * combinators.length)]}${selector}`;
  }
  return selector;
}

test('the rules an element matches are the ones the matcher matches, with the fast paths answering most of them', () => {
  for (let seed = 1; seed <= 12; seed += 1) {
    const next = rng(seed);
    const selectors = Array.from({ length: 160 }, () => selectorOf(next));
    // the plain cases a framework writes most: a class alone, an id alone
    selectors.push('.a', '.md\\:x', '#y', '.b .c', '#x .e', 'section .a');
    const css = selectors.map((s, i) => `${s} { --r${i}: 1 }`).join('\n');
    const source = new HtmlSource();
    source.setSource(documentOf(next), true);
    const sheet = parseStylesheet(css, 0);
    const rules = new Map(sheet.rules.map((rule) => [rule.declarations, rule]));
    const cascade = new Cascade([sheet], LOOK, 800, 600, 1);
    const candidates = (
      cascade as unknown as {
        _candidates(el: Element): { declarations: unknown }[];
      }
    )._candidates.bind(cascade);
    const elements: Element[] = [];
    const walk = (node: { children?: unknown[] }): void => {
      for (const child of (node.children ?? []) as Element[]) {
        if (child.type === 'tag') elements.push(child);
        walk(child);
      }
    };
    walk(source.document);
    // as a build asks, a whole document from the top down, and again as a
    // restyle in place does, outside a build
    for (const building of [true, false]) {
      if (building) cascade.beginSharing();
      for (const el of elements) {
        const got = candidates(el)
          .map((c) => rules.get(c.declarations as never)?.selector)
          .filter((s): s is string => s !== undefined)
          .sort();
        const want = sheet.rules
          .filter((rule) => is(el, rule.selector))
          .map((rule) => rule.selector)
          .sort();
        assert.deepStrictEqual(got, want, `seed ${seed}, <${el.name}>`);
      }
      if (building) cascade.endSharing();
    }
  }
});

test('a name a rule first asks of an ancestor after what is above an element was worked out is found there too', () => {
  // What is known above an element is kept to the names some rule has
  // asked of an ancestor, and a rule is first asked of when an element
  // reaches its bucket: here `.outer` is first asked by the last element,
  // after `.mid .a` had the names above `div.outer` worked out without it
  // — in a build, kept for the elements under it — and `.wide` by the
  // second rule an element asks, after the first had them worked out for
  // that element.
  const cases = [
    [
      '<div class="outer"><div class="mid"><p class="a">x</p></div><p class="late">y</p></div>',
      ['.mid .a', '.outer .late'],
    ],
    [
      '<div class="wide"><div class="mid"><p class="a b">x</p></div></div>',
      ['.mid .a', '.wide .b'],
    ],
  ] as const;
  for (const [markup, selectors] of cases) {
    for (const building of [true, false]) {
      const source = new HtmlSource();
      source.setSource(
        `<html><head></head><body>${markup}</body></html>`,
        true,
      );
      const sheet = parseStylesheet(
        selectors.map((s, i) => `${s} { --r${i}: 1 }`).join('\n'),
        0,
      );
      const rules = new Map(
        sheet.rules.map((rule) => [rule.declarations, rule]),
      );
      const cascade = new Cascade([sheet], LOOK, 800, 600, 1);
      const candidates = (
        cascade as unknown as {
          _candidates(el: Element): { declarations: unknown }[];
        }
      )._candidates.bind(cascade);
      if (building) cascade.beginSharing();
      const elements: Element[] = [];
      const walk = (node: { children?: unknown[] }): void => {
        for (const child of (node.children ?? []) as Element[]) {
          if (child.type === 'tag') elements.push(child);
          walk(child);
        }
      };
      walk(source.document);
      for (const el of elements) {
        const got = candidates(el)
          .map((c) => rules.get(c.declarations as never)?.selector)
          .filter((s): s is string => s !== undefined)
          .sort();
        const want = sheet.rules
          .filter((rule) => is(el, rule.selector))
          .map((rule) => rule.selector)
          .sort();
        assert.deepStrictEqual(
          got,
          want,
          `${building ? 'in' : 'outside'} a build, <${el.name} class="${el.attribs.class}">`,
        );
      }
      if (building) cascade.endSharing();
    }
  }
});
