// Table layout.
//
// Tables earn a formatting context of their own here rather than being
// approximated with flex, because the thing a table does that nothing else
// does is **size a column from every cell in it** — a constraint that runs
// across the grain of the box tree, and the reason a table cannot be
// expressed as nested rows of boxes without measuring twice and guessing.
//
// The documents this component exists for are full of them: exported
// reports, mail, anything generated by a template. So the auto algorithm is
// implemented rather than stubbed, and `table-layout: fixed` is implemented
// beside it because that is the one an author reaches for when the auto
// algorithm is too slow — which, on a table with a thousand rows, it is.
import { AUTO, isPct, resolveOrNull } from '../css/values.js';
import type { Len } from '../css/values.js';
import { Box } from './boxes.js';
import {
  clampHeight,
  layoutBlockIn,
  measureIntrinsicWidth,
  moveContent,
  moveTo,
  resolveEdges,
} from './block.js';
import type { LayoutContext } from './block.js';
import { firstBaselineIn } from './inline.js';
import { tableGrid } from './grid.js';
import type { Cell } from './grid.js';

/** Lay out a table's insides. Returns the content height. */
export function layoutTable(
  table: Box,
  ctx: LayoutContext,
  contentWidth: number,
): number {
  const { rows, captions, cells, columnCount, columnBoxes } = tableGrid(table);
  table.captionTop = 0;
  table.captionBottom = 0;
  if (!columnCount) {
    layoutCaptions(captions, ctx, table);
    return 0;
  }

  const style = table.style;
  // between the columns, and between the rows (CSS 2.1 17.6.1)
  const apart = style.borderCollapse !== 'collapse';
  const spacing = apart ? style.borderSpacing : 0;
  const rowSpacing = apart ? style.borderSpacingY : 0;
  const gaps = spacing * (columnCount + 1);
  const available = Math.max(0, contentWidth - gaps);

  for (const cell of cells) resolveEdges(cell.box, contentWidth);

  // a fixed layout needs a width to be fixed to; with `auto` a table is laid
  // out by its contents after all (CSS 2.1 17.5.2.1)
  const fixed = style.tableLayout === 'fixed' && style.width !== AUTO;
  const widths = fixed
    ? fixedColumns(cells, columnBoxes, columnCount, available, spacing)
    : autoColumns(
        cells,
        columnCount,
        available,
        ctx,
        contentWidth,
        style.width !== AUTO,
      );

  // --- place ---------------------------------------------------------------
  // An auto table is at least as wide as its widest caption can be (CSS 2.1
  // 17.5.2), and as its `min-width` asks; the columns share what that adds.
  if (style.width === AUTO) {
    let room = 0;
    if (captions.length) {
      room = captionMinimum(captions, ctx) - table.horizontalExtra - gaps;
    }
    const min = resolveOrNull(style.minWidth, contentWidth);
    if (min !== null) {
      const inner =
        style.boxSizing === 'border-box' ? min - table.horizontalExtra : min;
      room = Math.max(room, inner - gaps);
    }
    const sum = widths.reduce((a, b) => a + b, 0);
    if (room > sum) {
      for (let c = 0; c < columnCount; c += 1) {
        widths[c] +=
          sum > 0
            ? (widths[c] / sum) * (room - sum)
            : (room - sum) / columnCount;
      }
    }
  }

  const columnX: number[] = new Array<number>(columnCount);
  let x = table.contentX + spacing;
  for (let c = 0; c < columnCount; c += 1) {
    columnX[c] = x;
    x += widths[c] + spacing;
  }
  // A table with `width: auto` is as wide as its columns need, not as wide as
  // its container — it shrinks to fit, which is what makes a two-column table
  // in a wide document a small table rather than a pair of columns stranded
  // at the left of a full-width box. The columns were sized against the space
  // on offer, so this narrows it — but never past the least its columns can
  // be (CSS 2.1 17.5.2.2): a table whose words do not fit is wider than the
  // room, as a word is, and one beside a float goes below it.
  //
  // A table set to a width is as wide as it or its columns, whichever is the
  // wider: columns set wider than the table widen it.
  const used = x - table.contentX;
  let tableContentWidth = contentWidth;
  if (style.width === AUTO) {
    tableContentWidth = used;
    table.width = tableContentWidth + table.horizontalExtra;
  } else if (used > contentWidth) {
    tableContentWidth = used;
    table.width = used + table.horizontalExtra;
  }
  layoutCaptions(captions, ctx, table);

  const top = table.contentY + table.captionTop;
  let y = top;
  const rowTop: number[] = new Array<number>(rows.length);
  const rowHeight: number[] = new Array<number>(rows.length).fill(0);
  y += rowSpacing;

  // Size every cell at its column width first, so a row's height is the
  // tallest cell in it rather than the first one that was measured.
  for (const cell of cells) {
    const width = spannedWidth(widths, cell, spacing);
    ctx.layoutSubtree(cell.box, width);
    const specified = resolveOrNull(cell.box.style.height, NaN);
    if (specified !== null) {
      cell.box.height = Math.max(
        cell.box.height,
        specified + cell.box.verticalExtra,
      );
    }
  }
  // A cell aligned on the baseline — every value but `top`, `middle` and
  // `bottom` — hangs its first line on its first row's baseline, the lowest
  // of theirs from the row's top (CSS 2.1 17.5.3), and the row is as tall as
  // the cells hung from it need.
  const lift = baselineLifts(cells, rows.length);
  for (let i = 0; i < cells.length; i += 1) {
    const cell = cells[i];
    if (cell.rowSpan > 1) continue;
    rowHeight[cell.row] = Math.max(
      rowHeight[cell.row],
      lift[i] + cell.box.height,
    );
  }
  for (let r = 0; r < rows.length; r += 1) {
    const specified = resolveOrNull(rows[r].style.height, NaN);
    if (specified !== null) rowHeight[r] = Math.max(rowHeight[r], specified);
  }
  // A row-spanning cell only forces height when the rows it covers do not
  // already provide it — otherwise a `rowspan="3"` cell would make each of
  // its three rows as tall as all of it.
  for (let i = 0; i < cells.length; i += 1) {
    const cell = cells[i];
    if (cell.rowSpan <= 1) continue;
    const last = Math.min(rows.length - 1, cell.row + cell.rowSpan - 1);
    let covered = 0;
    for (let r = cell.row; r <= last; r += 1) covered += rowHeight[r];
    covered += rowSpacing * (last - cell.row);
    const missing = lift[i] + cell.box.height - covered;
    if (missing > 0) rowHeight[last] += missing;
  }

  // A table's own height, within its least and greatest, is a least
  // height: what its rows come short of it goes to them, in proportion to
  // what they have (CSS 2.1 17.5.3)
  const wanted = resolveOrNull(style.height, table.percentHeightBase);
  if (rows.length) {
    const extraBox = table.verticalExtra;
    const set =
      wanted === null
        ? 0
        : style.boxSizing === 'border-box'
          ? wanted
          : wanted + extraBox;
    const inner = clampHeight(table, set) - extraBox;
    let total = 0;
    for (const h of rowHeight) total += h;
    const extra = inner - total - rowSpacing * (rows.length + 1);
    if (extra > 0) {
      for (let r = 0; r < rows.length; r += 1) {
        rowHeight[r] +=
          total > 0 ? (extra * rowHeight[r]) / total : extra / rows.length;
      }
    }
  }

  for (let r = 0; r < rows.length; r += 1) {
    rowTop[r] = y;
    y += rowHeight[r] + rowSpacing;
  }

  for (let i = 0; i < cells.length; i += 1) {
    const cell = cells[i];
    const last = Math.min(rows.length - 1, cell.row + cell.rowSpan - 1);
    let height = 0;
    for (let r = cell.row; r <= last; r += 1) height += rowHeight[r];
    height += rowSpacing * (last - cell.row);
    const width = spannedWidth(widths, cell, spacing);
    const inner = cell.box.height;
    // `vertical-align` inside a cell moves the *content*, not the box: the
    // box fills the row, background and all, and the content sits top,
    // middle, bottom or on the row's baseline in it.
    let offset = lift[i];
    const va = cell.box.style.verticalAlign;
    if (va === 'middle') offset = Math.max(0, (height - inner) / 2);
    else if (va === 'bottom') offset = Math.max(0, height - inner);
    moveTo(cell.box, columnX[cell.column], rowTop[cell.row]);
    moveContent(cell.box, offset);
    cell.box.width = width;
    cell.box.height = Math.max(inner, height);
  }

  // where the grid lines fell, for the collapsed borders drawn along them
  const collapsed = table.collapsed;
  if (collapsed && collapsed.columns === columnCount) {
    const last = columnCount - 1;
    collapsed.lineX = columnX.map((cx) => cx - table.x);
    collapsed.lineX.push(columnX[last] + widths[last] - table.x);
    collapsed.lineY = rowTop.map((ry) => ry - table.y);
    const bottom = rows.length - 1;
    collapsed.lineY.push(rowTop[bottom] + rowHeight[bottom] - table.y);
  }

  for (let r = 0; r < rows.length; r += 1) {
    const row = rows[r];
    row.x = table.contentX;
    row.y = rowTop[r];
    row.width = tableContentWidth;
    row.height = rowHeight[r];
  }
  for (const child of table.children) {
    if (child.kind !== 'table-row-group') continue;
    const groupRows = child.children.filter((row) => row.kind === 'table-row');
    if (!groupRows.length) continue;
    child.x = table.contentX;
    child.y = groupRows[0].y;
    child.width = tableContentWidth;
    child.height =
      groupRows[groupRows.length - 1].y +
      groupRows[groupRows.length - 1].height -
      child.y;
  }

  return y - top;
}

/**
 * A table's captions, which are outside the table box (CSS 2.1 17.4): as
 * wide as its border box, the ones on top above its border, and the ones
 * at the bottom laid out here and placed below it by `finishCaptions`,
 * once the table's height is known.
 */
function layoutCaptions(captions: Box[], ctx: LayoutContext, table: Box): void {
  let y = table.y;
  for (const caption of captions) {
    // laid out at the offset its margins give it across the table, which
    // is where it stays across
    layoutBlockIn(caption, ctx, table.width);
    const height = caption.marginTop + caption.height + caption.marginBottom;
    if (caption.style.captionSide === 'bottom') {
      table.captionBottom += height;
      continue;
    }
    moveTo(caption, table.x + caption.x, y + caption.marginTop);
    y += height;
    table.captionTop += height;
  }
}

/** The narrowest the widest caption can be, margins in: its own width
 *  where it has one, and its longest word where it has not. */
function captionMinimum(captions: Box[], ctx: LayoutContext): number {
  let widest = 0;
  for (const caption of captions) {
    const width = measureIntrinsicWidth(caption, ctx, 1);
    widest = Math.max(widest, width + caption.marginLeft + caption.marginRight);
  }
  return widest;
}

/** The table box has its height: the captions go around it, the bottom
 *  ones below it, and the box grows to hold them. */
export function finishCaptions(table: Box): void {
  if (!table.captionTop && !table.captionBottom) return;
  let y = table.y + table.captionTop + table.height;
  for (const caption of table.children) {
    if (caption.kind !== 'table-caption') continue;
    if (caption.style.captionSide !== 'bottom') continue;
    moveTo(caption, table.x + caption.x, y + caption.marginTop);
    y += caption.marginTop + caption.height + caption.marginBottom;
  }
  table.height += table.captionTop + table.captionBottom;
}

function spannedWidth(widths: number[], cell: Cell, spacing: number): number {
  let width = 0;
  const last = Math.min(widths.length - 1, cell.column + cell.colSpan - 1);
  for (let c = cell.column; c <= last; c += 1) width += widths[c];
  return width + spacing * (last - cell.column);
}

/**
 * `table-layout: fixed`: the columns and the first row decide, and the rest
 * of the table is not measured at all, which is the whole point of it (CSS
 * 2.1 17.5.2.1). A column with a `width` sets its own; failing that, a cell
 * of the first row with one sets the columns it spans, by its border box and
 * less the spacing between them; the columns left share what remains, and
 * where nothing remains, what is left of a table wider than its columns is
 * shared among all of them.
 */
function fixedColumns(
  cells: Cell[],
  columnBoxes: (Box | null)[],
  columnCount: number,
  available: number,
  spacing: number,
): number[] {
  const widths: number[] = new Array<number>(columnCount).fill(0);
  const set: boolean[] = new Array<boolean>(columnCount).fill(false);
  for (let c = 0; c < columnCount; c += 1) {
    const column = columnBoxes[c];
    const px = column ? lengthAgainst(column.style.width, available) : null;
    if (px === null) continue;
    widths[c] = Math.max(0, px);
    set[c] = true;
  }
  for (const cell of cells) {
    if (cell.row > 0) break;
    const px = lengthAgainst(cell.box.style.width, available);
    if (px === null) continue;
    const box = cell.box;
    const outer =
      box.style.boxSizing === 'border-box'
        ? Math.max(px, box.horizontalExtra)
        : px + box.horizontalExtra;
    const last = Math.min(columnCount, cell.column + cell.colSpan);
    let taken = spacing * (last - cell.column - 1);
    let open = 0;
    for (let c = cell.column; c < last; c += 1) {
      if (set[c]) taken += widths[c];
      else open += 1;
    }
    if (!open) continue;
    const each = Math.max(0, outer - taken) / open;
    for (let c = cell.column; c < last; c += 1) {
      if (set[c]) continue;
      widths[c] = each;
      set[c] = true;
    }
  }
  let used = 0;
  let unset = 0;
  for (let c = 0; c < columnCount; c += 1) {
    if (set[c]) used += widths[c];
    else unset += 1;
  }
  const remaining = Math.max(0, available - used);
  if (unset) {
    for (let c = 0; c < columnCount; c += 1) {
      if (!set[c]) widths[c] = remaining / unset;
    }
  } else if (remaining > 0 && columnCount) {
    for (let c = 0; c < columnCount; c += 1) {
      widths[c] +=
        used > 0 ? (widths[c] / used) * remaining : remaining / columnCount;
    }
  }
  return widths;
}

/**
 * The auto algorithm: measure every cell's max-content and min-content
 * width, then distribute.
 *
 * The distribution is the part worth stating. When the max-content widths
 * fit, they are used — a small table is exactly as wide as its contents.
 * When they do not, the surplus over each column's minimum is scaled down in
 * proportion, so a column of long prose gives up more than a column of
 * dates. A column with an explicit `width` is honoured before either.
 */
function autoColumns(
  cells: Cell[],
  columnCount: number,
  available: number,
  ctx: LayoutContext,
  containingWidth: number,
  fill: boolean,
): number[] {
  const max: number[] = new Array<number>(columnCount).fill(0);
  const min: number[] = new Array<number>(columnCount).fill(0);
  const explicit: (number | null)[] = new Array<number | null>(
    columnCount,
  ).fill(null);

  for (const cell of cells) {
    // Two probe layouts per cell: unconstrained for max-content, and at a
    // width of 1 for min-content — which the line breaker answers by
    // breaking at every opportunity, so the widest line is the longest
    // unbreakable word.
    //
    // Cached on the box, because intrinsic widths are width-independent by
    // definition — measuring them per layout pass made a *resize* of a
    // 500-row table cost as much as its first layout (223ms of re-probing
    // measured against 10ms with the cache). The cache's invalidation rule
    // is the box's lifetime: any DOM or style change rebuilds the tree.
    if (cell.box.intrinsicMaxContent < 0) {
      cell.box.intrinsicMaxContent = measureIntrinsicWidth(
        cell.box,
        ctx,
        Infinity,
      );
      cell.box.intrinsicMinContent = measureIntrinsicWidth(cell.box, ctx, 1);
    }
    const cellMax = cell.box.intrinsicMaxContent;
    const cellMin = cell.box.intrinsicMinContent;

    const len = cell.box.style.width;
    const width = len === AUTO ? null : lengthAgainst(len, containingWidth);
    if (cell.colSpan === 1) {
      max[cell.column] = Math.max(max[cell.column], cellMax);
      min[cell.column] = Math.max(min[cell.column], cellMin);
      if (width !== null) {
        explicit[cell.column] = Math.max(
          explicit[cell.column] ?? 0,
          width + cell.box.horizontalExtra,
        );
      }
    } else {
      // A spanning cell contributes to its columns only when they cannot
      // already hold it, spread evenly — which is the spec's rule reduced to
      // the part that matters visually.
      const last = Math.min(columnCount - 1, cell.column + cell.colSpan - 1);
      let currentMax = 0;
      let currentMin = 0;
      for (let c = cell.column; c <= last; c += 1) {
        currentMax += max[c];
        currentMin += min[c];
      }
      const spread = last - cell.column + 1;
      if (cellMax > currentMax) {
        const each = (cellMax - currentMax) / spread;
        for (let c = cell.column; c <= last; c += 1) max[c] += each;
      }
      if (cellMin > currentMin) {
        const each = (cellMin - currentMin) / spread;
        for (let c = cell.column; c <= last; c += 1) min[c] += each;
      }
    }
  }

  // what the columns' content alone asks, before their set widths: the
  // least a column gives way to when the table has less room than its
  // cells' widths want, as beside a float
  const least = min.slice();
  for (let c = 0; c < columnCount; c += 1) {
    if (explicit[c] !== null) {
      max[c] = Math.max(max[c], explicit[c] as number);
      min[c] = Math.max(min[c], Math.min(explicit[c] as number, max[c]));
    }
    min[c] = Math.min(min[c], max[c]);
  }

  const totalMax = max.reduce((a, b) => a + b, 0);
  if (totalMax <= available) {
    // Everything fits. A table with a width of its own still fills it (CSS
    // 2.1 17.5.2.2): the columns not set to a width take the rest in
    // proportion to what they asked for, or every column does where all are
    // set. Returned as asked, `<table width="600">` drew its cells at their
    // content's width and left the rest of its 600 empty.
    if (!fill || available <= totalMax) return max;
    const set = explicit.every((w) => w !== null);
    let weight = 0;
    let count = 0;
    for (let c = 0; c < columnCount; c += 1) {
      if (!set && explicit[c] !== null) continue;
      weight += max[c];
      count += 1;
    }
    const extra = available - totalMax;
    return max.map((m, c) =>
      !set && explicit[c] !== null
        ? m
        : m + (weight > 0 ? (extra * m) / weight : extra / count),
    );
  }
  const totalMin = min.reduce((a, b) => a + b, 0);
  if (totalMin >= available) {
    // Less room than the cells' widths want: a width a cell was set to
    // gives way first, down to what its content asks, and a table never
    // goes narrower than its words (CSS 2.1 17.5.2.2), which it overflows.
    const totalLeast = least.reduce((a, b) => a + b, 0);
    if (totalLeast >= available) return least;
    const give = totalMin - totalLeast;
    return min.map(
      (m, c) => m - ((m - least[c]) / give) * (totalMin - available),
    );
  }
  const slack = available - totalMin;
  const surplus = totalMax - totalMin;
  return max.map((m, c) => min[c] + ((m - min[c]) / surplus) * slack);
}

function lengthAgainst(len: Len, base: number): number | null {
  if (len === AUTO) return null;
  if (isPct(len)) return Number.isFinite(base) ? (len.pct / 100) * base : null;
  return len;
}

/**
 * How far each cell's content moves down to put its baseline on its first
 * row's: 0 for a cell aligned `top`, `middle` or `bottom`, which is placed
 * once the row's height is known. A cell's baseline is its first line box's,
 * at any depth, or the bottom of its content where it has none (CSS 2.1
 * 17.5.3); it is taken as laid out, from the cell's top. An empty cell has
 * nothing to align and says nothing about the row's, as in a browser: its
 * content's bottom is its height, which would hang every other cell in the
 * row from the bottom of a cell given a height and nothing in it.
 */
function baselineLifts(cells: Cell[], rowCount: number): number[] {
  const lift = new Array<number>(cells.length).fill(0);
  let any = false;
  for (const cell of cells) {
    const va = cell.box.style.verticalAlign;
    if (va !== 'top' && va !== 'middle' && va !== 'bottom') any = true;
  }
  if (!any) return lift;
  const own = new Array<number>(cells.length).fill(NaN);
  const row = new Array<number>(rowCount).fill(-Infinity);
  for (let i = 0; i < cells.length; i += 1) {
    const box = cells[i].box;
    const va = box.style.verticalAlign;
    if (va === 'top' || va === 'middle' || va === 'bottom') continue;
    const first = firstBaselineIn(box);
    if (first === null && !holdsFlow(box)) continue;
    own[i] =
      first !== null
        ? first - box.y
        : box.height - box.padBottom - box.borderBottom;
    row[cells[i].row] = Math.max(row[cells[i].row], own[i]);
  }
  for (let i = 0; i < cells.length; i += 1) {
    if (own[i] === own[i]) lift[i] = row[cells[i].row] - own[i];
  }
  return lift;
}

/** Whether a cell has anything in flow in it. */
function holdsFlow(box: Box): boolean {
  for (const child of box.children) {
    if (child.outOfFlow || child.isFloat) continue;
    if (child.kind === 'text' && /^\s*$/.test(child.text)) continue;
    return true;
  }
  return false;
}
