// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      // reference/ is generated at build time by scripts/sync-docs.mjs from
      // the repo's docs/ directory; let Docusaurus pick up whatever is there,
      // so a new page needs no edit here.
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
  ],
};

module.exports = sidebars;
